// Icons
import {
  Award,
  ShoppingBag,
  ShoppingCart,
  MapPin,
  User as UserIcon,
  Menu,
  Search,
  Plus,
  Trash2,
  Check,
  ExternalLink,
  CheckCircle,
  X,
  ChevronRight,
  ChevronLeft,
  ChevronUp,
  ChevronDown,
  Home,
  Settings,
  LogOut,
  Clock,
  DollarSign,
  Bike,
  Store,
  CreditCard,
  Edit2,
  Camera,
  Filter,
  Mail,
  Phone,
  Eye,
  EyeOff,
  Star,
  ArrowUp,
  ArrowDown,
  Calendar,
  MessageSquare,
  Zap,
  TrendingUp,
  AlertTriangle,
  Megaphone,
  BarChart2,
  RotateCcw,
} from "lucide-react";

// URL del backend. En producción Vercel usará la variable de entorno, en local usará localhost.
export const API_URL = import.meta.env.VITE_API_URL || "http://localhost:3001";

// Social Login IDs
export const GOOGLE_CLIENT_ID = (
  import.meta.env.VITE_GOOGLE_CLIENT_ID || ""
).trim();
export const APPLE_CLIENT_ID = import.meta.env.VITE_APPLE_CLIENT_ID || "";

export const Icons = {
  Award,
  ShoppingBag,
  ShoppingCart,
  MapPin,
  User: UserIcon,
  Menu,
  Search,
  Plus,
  Trash2,
  Check,
  ExternalLink,
  CheckCircle,
  X,
  ChevronRight,
  ChevronLeft,
  ChevronUp,
  ChevronDown,
  Home,
  Settings,
  LogOut,
  Clock,
  DollarSign,
  Bike,
  Store,
  CreditCard,
  Edit2,
  Camera,
  Filter,
  Mail,
  Phone,
  Eye,
  EyeOff,
  Star,
  ArrowUp,
  ArrowDown,
  Calendar,
  MessageSquare,
  Zap,
  TrendingUp,
  AlertTriangle,
  Megaphone,
  BarChart2,
  RotateCcw,
};

export const ALLOWED_EMAILS = [
  "@gmail.com",
  "@hotmail.com",
  "@outlook.com",
  "@yahoo.com",
];

// Límites de productos por tipo de suscripción
export const SUBSCRIPTION_LIMITS = {
  STANDARD: 20,
  PREMIUM: 50,
  BLACK: 130,
};
